"""

Revision ID: 4dc85a06af07
Revises: kincone_transportation_001
Create Date: 2025-05-31 09:34:12.384573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc85a06af07'
down_revision: Union[str, None] = 'kincone_transportation_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_period_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('employee_number', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('work_days', sa.Integer(), nullable=True),
    sa.Column('total_work_time', sa.String(), nullable=True),
    sa.Column('regular_work_time', sa.String(), nullable=True),
    sa.Column('actual_work_time', sa.String(), nullable=True),
    sa.Column('overtime_work_time', sa.String(), nullable=True),
    sa.Column('late_night_work_time', sa.String(), nullable=True),
    sa.Column('holiday_work_time', sa.String(), nullable=True),
    sa.Column('paid_leave_used', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('paid_leave_remaining', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('absence_days', sa.Integer(), nullable=True),
    sa.Column('tardiness_count', sa.Integer(), nullable=True),
    sa.Column('early_leave_count', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_period_id'], ['calculation_periods.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
