"""Remove department and position, add resignation_date

Revision ID: bcc93efca905
Revises: fb97019cfa0c
Create Date: 2025-05-31 04:23:01.619080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc93efca905'
down_revision: Union[str, None] = 'fb97019cfa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('resignation_date', sa.DateTime(), nullable=True))
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'resignation_date')
    # ### end Alembic commands ###
