"""remove_expense_records_table

Revision ID: c607a9976da4
Revises: 5d8ae3521332
Create Date: 2025-05-31 07:31:50.568911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c607a9976da4'
down_revision: Union[str, None] = '5d8ae3521332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expense_records_id', table_name='expense_records')
    op.drop_table('expense_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('calculation_period_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expense_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receipt_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('freee_transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['calculation_period_id'], ['calculation_periods.id'], name='expense_records_calculation_period_id_fkey'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='expense_records_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='expense_records_pkey')
    )
    op.create_index('ix_expense_records_id', 'expense_records', ['id'], unique=False)
    # ### end Alembic commands ###
