"""

Revision ID: dce3c82d8698
Revises: 4dc85a06af07
Create Date: 2025-05-31 09:58:18.039421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce3c82d8698'
down_revision: Union[str, None] = '4dc85a06af07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'freee_name')
    op.drop_column('employees', 'kincone_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('kincone_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('freee_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
