"""Add employee additional fields

Revision ID: fb97019cfa0c
Revises: 
Create Date: 2025-05-31 04:08:26.468222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb97019cfa0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('kincone_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('freee_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('kiwi_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('remote_allowance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'remote_allowance')
    op.drop_column('employees', 'kiwi_name')
    op.drop_column('employees', 'freee_name')
    op.drop_column('employees', 'kincone_name')
    # ### end Alembic commands ###
